//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceDataHandler.GYReportServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gyreport.hshfy.sh.cn", ConfigurationName="GYReportServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://gyreport.hshfy.sh.cn 的元素名称 index_code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gyreport.hshfy.sh.cn/getIndexValue", ReplyAction="*")]
        WebServiceDataHandler.GYReportServiceReference.getIndexValueResponse getIndexValue(WebServiceDataHandler.GYReportServiceReference.getIndexValueRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIndexValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIndexValue", Namespace="http://gyreport.hshfy.sh.cn", Order=0)]
        public WebServiceDataHandler.GYReportServiceReference.getIndexValueRequestBody Body;
        
        public getIndexValueRequest() {
        }
        
        public getIndexValueRequest(WebServiceDataHandler.GYReportServiceReference.getIndexValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gyreport.hshfy.sh.cn")]
    public partial class getIndexValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string index_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string beg_year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string beg_month;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string beg_day;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string end_year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string end_month;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string end_day;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fybm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string bmbm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string rybm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string others;
        
        public getIndexValueRequestBody() {
        }
        
        public getIndexValueRequestBody(string index_code, string beg_year, string beg_month, string beg_day, string end_year, string end_month, string end_day, string fybm, string bmbm, string rybm, string others) {
            this.index_code = index_code;
            this.beg_year = beg_year;
            this.beg_month = beg_month;
            this.beg_day = beg_day;
            this.end_year = end_year;
            this.end_month = end_month;
            this.end_day = end_day;
            this.fybm = fybm;
            this.bmbm = bmbm;
            this.rybm = rybm;
            this.others = others;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIndexValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIndexValueResponse", Namespace="http://gyreport.hshfy.sh.cn", Order=0)]
        public WebServiceDataHandler.GYReportServiceReference.getIndexValueResponseBody Body;
        
        public getIndexValueResponse() {
        }
        
        public getIndexValueResponse(WebServiceDataHandler.GYReportServiceReference.getIndexValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gyreport.hshfy.sh.cn")]
    public partial class getIndexValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getIndexValueResult;
        
        public getIndexValueResponseBody() {
        }
        
        public getIndexValueResponseBody(string getIndexValueResult) {
            this.getIndexValueResult = getIndexValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServiceDataHandler.GYReportServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServiceDataHandler.GYReportServiceReference.WebService1Soap>, WebServiceDataHandler.GYReportServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceDataHandler.GYReportServiceReference.getIndexValueResponse WebServiceDataHandler.GYReportServiceReference.WebService1Soap.getIndexValue(WebServiceDataHandler.GYReportServiceReference.getIndexValueRequest request) {
            return base.Channel.getIndexValue(request);
        }
        
        public string getIndexValue(string index_code, string beg_year, string beg_month, string beg_day, string end_year, string end_month, string end_day, string fybm, string bmbm, string rybm, string others) {
            WebServiceDataHandler.GYReportServiceReference.getIndexValueRequest inValue = new WebServiceDataHandler.GYReportServiceReference.getIndexValueRequest();
            inValue.Body = new WebServiceDataHandler.GYReportServiceReference.getIndexValueRequestBody();
            inValue.Body.index_code = index_code;
            inValue.Body.beg_year = beg_year;
            inValue.Body.beg_month = beg_month;
            inValue.Body.beg_day = beg_day;
            inValue.Body.end_year = end_year;
            inValue.Body.end_month = end_month;
            inValue.Body.end_day = end_day;
            inValue.Body.fybm = fybm;
            inValue.Body.bmbm = bmbm;
            inValue.Body.rybm = rybm;
            inValue.Body.others = others;
            WebServiceDataHandler.GYReportServiceReference.getIndexValueResponse retVal = ((WebServiceDataHandler.GYReportServiceReference.WebService1Soap)(this)).getIndexValue(inValue);
            return retVal.Body.getIndexValueResult;
        }
    }
}
